### ISSUE TITLE
unknow problem about ble-replay

### ISSUE THREAD

**Issue by Taolaw** [nccgroup/BLESuite#13]
Follow the instructions to perform the results:

```bash
root@kali:~# ble-replay -i 0 -d AC:9A:22:C4:84:E8 -p '/root/tmp/btsnoop_hci.log' -r
loading file
Btsnoop capture file version 1, type 1002
DEBUG:blesuite.connection_manager:creating central
DEBUG:blesuite.pybt.stack:Trying to set reuseaddr
DEBUG:blesuite.pybt.stack:Settings ins reuse
```

The program stopped here and there was no response. I used the wireshark to capture the Bluetooth port and only sent a `hci_cmd` package. The content is: `01 09 10 00`, I don't know what the problem is. I tried  https://github.com/nccgroup/BLE-Replay  this tool, but the effect is even worse, as shown below:

```bash
root@kali:~/code/BLE-Replay-master# python ble-replay.py -h
Traceback (most recent call last):
  File "ble-replay.py", line 1, in <module>
    import hci_parser
  File "/root/code/BLE-Replay-master/hci_parser.py", line 3, in <module>
    import util
  File "/root/code/BLE-Replay-master/util.py", line 4, in <module>
    from blesuite.bleServiceManager import bleServiceWriteToHandle
ImportError: No module named bleServiceManager
```
I used `grep` to search the directory of `BLEsulte`, and did not find the string about `bleServiceManager`. Is this the reason for the version aid change? Is this class still useful?

I hope you can see, thank you, I urgently need to do some testing, I hope `BLEsuite` can help me.

**Comment by MrARM** [comment]
This isn't the right place to post this issue as this isn't BLE-Replay, but I also stumbled upon this issue and found a solution. 

BLE-Replay was built on BLESuite 1.0.0(Based on the commit dates), so you will need to downgrade to that version. You can do that by resetting your git repo to the last commit 1.0 had.
`git reset --hard 58574a2e48`, then reinstall and try again
